version: '3.8'

services:
  phantom-mask:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: development
    ports:
      - "80:3000"
    volumes:
      - .:/app
    container_name: my-project
